### PR TITLE
added mockup notebooks, vignettes and icons

### PR DESCRIPTION
**Pull request by LucaMarconato**

### CODE REVIEW

**Comment by LucaMarconato** [comment]
I would merge and maybe after the merge (or after the paper), replace the code that I use for displaying the image gallery with the one that is used in squidpy.

**Comment by LucaMarconato** [comment]
@giovp I merged your vignettes from main.

Comments:
* Note that the gallery with icons is defined in `notebooks.md`, I am importing this in the docs in spatialdata instead of index. To try it you have to set the submodule in the spatialdata docs to use this branch, I think it works well this way.
* I have removed the Xenium + Visium notebook and the Lundeberg notebook from the rendered docs, but I keep the files in this repo inside the folder `paper-reproducibility`.

**Comment by LucaMarconato** [comment]
I would change the way we deal with the icons for the gallery in a separate pr. So this PR should be ready to merge as it is.

**Review by kevinyamauchi — APPROVED** [review]
Thanks, @LucaMarconato ! This looks good to me. I didn't look super closely, but I think it's worth getting these in and we can iterate further as we go. I'll let @giovp take a pass and merge if he wishes.

**Comment by LucaMarconato** [comment]
Thanks @kevinyamauchi! Btw I have just pushed the densenet example, I ask you to have a look at it please.

**Comment by kevinyamauchi** [comment]
Thanks for adding the deep learning notebook, @LucaMarconato . Is there any way to suppress the geopandas warning during training? Also, regarding the multiprocessing, can we set the number of workers to 0 to deactivate it?

In any case, since this is already a nice chunk of work, I think we should move forward with this. We can circle back and clean up the example later.

**Comment by LucaMarconato** [comment]
Re the warnings, I want to spend some time at some point addressing warning in general. For instance there is also a ome-zarr warning that leaks trough (when we load the data). But I agree, we should try suppressing them here.

Re the multiprocessing we can disable it and see also how much performance is impacted. I'll add it to the todo list.

**Pull request merged**
