### PR TITLE
add xenium example

### PR DESCRIPTION
**Pull request by giovp**
should be merged after #93  and after https://github.com/scverse/spatialdata-plot/pull/237

### CODE REVIEW

**Comment by melonora** [comment]
Maybe with the bounding box query also refer to the spatial_query notebook.

**Comment by melonora** [comment]
Also maybe with the last screenshot of napari explain that the user sees the exclamation warning in front of the element to warn that visualizing might take long.

**Review by melonora — APPROVED** [review]
2 minor comments but otherwise LGTM!

**Comment by LucaMarconato** [comment]
Thanks for the notebook and for the suggestions, I applied them. I also added a plot for the 4 channels used in the multimodal segmentation.

image

**Review by LucaMarconato — APPROVED** [review]

**Pull request merged**
