### PR TITLE
Pass plot notebooks

### PR DESCRIPTION
**Pull request by melonora**
PR fixing all plots for the notebooks

### CODE REVIEW

**Comment by melonora** [comment]
The plots are all fixed as far as I can tell right now. Here and there there are issues with spatialdata-plot for which I have opened issues. Some that I will address still. 

For squidpy there is only the question what the intent was for the cell in which it is stated that currently multi-table is broken.

**Comment by giovp** [comment]
looks great @melonora ! from the reviewNB it seems like the output were not visible, but from the built docs they are! so I think we are good to go, LGTM!

FYI: I'm doing the xenium use case off #93 and once done will ask for review and then merge #93 and the xenium one

**Review by giovp — APPROVED** [review]

**Comment by melonora** [comment]
Great, I'll be available for review.

**Comment by LucaMarconato** [comment]
Thanks, I rendered the figures (except for the mibitof notebook, which is not working as reported in spatialdata-plot). Merging!

**Pull request merged**
