### PR TITLE
add speed up demonstration of datashader

### PR DESCRIPTION
**Pull request by Sonja-Stockhaus**
Little benchmark to demonstrate in which cases it is helpful to use datashader to increase rendering speed

### CODE REVIEW

**Comment by LucaMarconato** [comment]
Thanks for the PR, this is very informative! Just a few minor comments:
- [ ] I'd remove the variables `mpl_sds` and `ds_sds` as they are not used (also, maybe you have already seen, the developers don't recommend to compute these statistics https://docs.python.org/3/library/timeit.html#timeit.Timer.repeat).
- [ ] The empirical indication that for ~1000 polygons on datashader is faster is very useful! Could you please also add a section to check this for points and circles?

Thanks a lot!

**Comment by LucaMarconato** [comment]
- [ ] Regarding the failing docs, it seems that it can be fixed by using this `myst` configuration setting: https://github.com/executablebooks/MyST-Parser/issues/519#issuecomment-1037239655, in `conf.py`.

**Comment by timtreis** [comment]
> * [ ]  Regarding the failing docs, it seems that it can be fixed by using this `myst` configuration setting: [WARNING reference target not found, even though reference exists executablebooks/MyST-Parser#519 (comment)](https://github.com/executablebooks/MyST-Parser/issues/519#issuecomment-1037239655), in `conf.py`.

We actually already seem to have that. Will try a html workaround

**Comment by timtreis** [comment]
@Sonja-Stockhaus @LucaMarconato I fixed some things that were causing warnings in other notebooks. Apparently, this fixed it.

**Comment by timtreis** [comment]
@Sonja-Stockhaus I modified your notebook slightly to have less redundant code. For testing I reduced the number of points. Will rerun over-night with enough `Points` to see the effect. 

However, for merging I'd wait until your main PR is merged because I want these to be real version accessible from PyPi.
image

**Comment by LucaMarconato** [comment]
@timtreis ready to merge??

**Comment by timtreis** [comment]
Not yet. On the one hand is datashader not faster for points, so that's weird. And then I wanted to first release sonjas feature branch so that the watermark has an actual release version attached and not a GitHub commit

**Pull request merged**
