### PR TITLE
Tables

### PR DESCRIPTION
**Pull request by melonora**
This PR fixes several errors in the aggregation notebook when using the multi_table branch of the SpatialData repo. Also removed commented out code that was commented because of an issue with not being able to plot columns of an element.

### CODE REVIEW

**Comment by LucaMarconato** [comment]
I just noticed that in https://github.com/scverse/spatialdata-notebooks/pull/75, we have this plot
Screenshot 2024-02-29 at 23 46 58
while in this branch we have this
Screenshot 2024-02-29 at 23 46 31

Hence at least one of the categorical labeling seems to be incorrect. I think this is related to this bug: https://github.com/scverse/spatialdata-plot/issues/214.

**Comment by LucaMarconato** [comment]
The could be a reappearance of this https://github.com/scverse/spatialdata-plot/issues/104, which in theory was fixed.

**Comment by melonora** [comment]
will check tomorrow:) there is also the issue with alpha when using color.

**Comment by melonora** [comment]
but at least the notebook runs

**Comment by LucaMarconato** [comment]
Could be also related to this: https://github.com/scverse/spatialdata-plot/issues/178, but I think it got fixed (and with the new join APIs it would be straightforward to fix).

**Comment by LucaMarconato** [comment]
> but at least the notebook runs

Yes! Thanks 🚀

**Pull request merged**
