### PR TITLE
illustration notebook for rasterization & multiscale images

### PR DESCRIPTION
**Pull request by Sonja-Stockhaus**

### CODE REVIEW

**Comment by LucaMarconato** [comment]
Hi, nice notebook! Please let me know if it's ready for review 😊

**Comment by Sonja-Stockhaus** [comment]
Hi @LucaMarconato! Good point, I kind of forgot about this PR, thanks for bringing it up! It's done and ready for review.

**Comment by timtreis** [comment]
<p>Okay!</p><p> </p>

---

 <a href='https://app.reviewnb.com/scverse/spatialdata-notebooks/pull/62/discussion/#comment-1883739777'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Sonja-Stockhaus** [comment]
<p>The image is just too small to see a large effect. There is no larger single-scale image, but I illustrate it with the largest image in the multi-scale image (very last image in the notebook). That just doesn't belong in the single-scale section imo</p><p> </p>

---

 <a href='https://app.reviewnb.com/scverse/spatialdata-notebooks/pull/62/discussion/#comment-1883739737'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by Sonja-Stockhaus** [comment]
Thanks for the feedback @timtreis! I updated the notebook including most of your input

**Review by LucaMarconato — APPROVED** [review]

**Comment by LucaMarconato** [comment]
Very nice and clear, good job! Pre-approving only with one minor comment. I guess that dpi and figsize can be specified also before calling the plotting function (e.g. `plt.figure()`) and by passing the `ax` to `plt.show()`.

I would show this as an extra comment to the notebook since it would be useful in scenarios like having multiple subplots manually created by the user.

**Comment by timtreis** [comment]
@LucaMarconato Do you have any idea why the build fails? It's not modifying the toml

**Comment by LucaMarconato** [comment]
I also had some weird problems with the docs today, I was getting a different unexpected error message and simply manually retriggering the build made the docs pass. Let's see if it works also for this PR.

**Comment by LucaMarconato** [comment]
No luck, maybe it's a problem with dependencies (the error message looks like the one here https://github.com/scverse/napari-spatialdata/issues/78).

**Comment by timtreis** [comment]
Fixed it by adjusting the headline levels in @Sonja-Stockhaus notebook, added it to the menu and also added the following change to the .toml because the warning told me to
image

**Pull request merged**
