### PR TITLE
Added images to plots in bb query notebook

### PR DESCRIPTION
**Pull request by LucaMarconato**
@timtreis @Sonja-Stockhaus there seems to be a bug in the spatial query notebook around a spatialdata-plot call, could you please have a look? Thanks

### CODE REVIEW

**Comment by Sonja-Stockhaus** [comment]
@LucaMarconato when downloading the data set from the link in the notebook (https://s3.embl.de/spatialdata/spatialdata-sandbox/visium.zip) I think I get different data than the one in the notebook. Bc the coordinate systems are named ST8059048 and ST8059049 and in the original notebook it's ST8059050 and ST8059051. The plots also look slightly different.

It doesn't matter for the bugfix but I just thought I'd let you know bc I also didn't find the correct dataset

**Comment by timtreis** [comment]
Same for me, I think those changed at one point.

**Comment by LucaMarconato** [comment]
Thanks for pointing this out, I will track this in a issue. I will re-enable the script uploading the data in S3, I think the notebook is correct and the data in S3 has not been updated.

**Comment by LucaMarconato** [comment]
I have temporarily replaced the static plots with napari plots in https://github.com/scverse/spatialdata-notebooks/pull/55 so that the users can reproduce the visualzations, I will put them back with this PR when it's ready. Thanks for your help.

**Comment by timtreis** [comment]
Hey @LucaMarconato, fixed the notebook. Can you confirm? 

There is one final napari screenshot that I didn't delete because it was there before, shall I delete and then merge?
image

**Comment by LucaMarconato** [comment]
Thanks @timtreis, which branch of `spatialdata-plot` shall I use to reproduce?

**Comment by timtreis** [comment]
Ah sorry, the transformations refactoring branch.

**Comment by LucaMarconato** [comment]
Looks great thank you!
Please add also these lines of code in the last plot
```python
cropped_sdata.pl.render_images().pl.show(ax=ax)
cropped_sdata2.pl.render_images().pl.show(ax=ax)
```
and make the plot a bit larger.

Then the screenshot Jupyter cell (and the corresponding file in `attachments`) can be removed.

**Comment by timtreis** [comment]
@LucaMarconato managed to fix the CI error, you just need to figure out which exact data name should be used (48/49/50?), then it's good to merge 👍

**Comment by LucaMarconato** [comment]
I've just verified, it's 50. Gonna update the notebook and merge. Thanks for the fix!

**Comment by LucaMarconato** [comment]
@timtreis @Sonja-Stockhaus, please redownload the visium.zarr data, the correct one should have the FOVs 50, 52. Tomorrow, unless the nightly upload job fails, you should be able to see the correct data.

Also, please rename the file to `visium_brain.zarr`. Other notebooks use the Visium breast cancer dataset and it is also called `visium.zarr` in the notebook, so let's use `visium_brain.zarr` here to distinguish them.

**Pull request merged**
